"""
EVE Online Asset Tracker - Flask Application
Test Application #1 - MOCK DATA ONLY
"""

from flask import Flask, render_template, request, redirect, url_for, flash, jsonify
import sqlite3
from datetime import datetime
import os
import json
import subprocess

app = Flask(__name__)
app.secret_key = 'eve-asset-tracker-secret-key'
DB_PATH = 'eve_assets.db'

# Google APIs imports
try:
    from google.oauth2 import service_account
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload, MediaInMemoryUpload
    GOOGLE_APIS_AVAILABLE = True
except ImportError:
    GOOGLE_APIS_AVAILABLE = False

# Credentials path
CREDENTIALS_PATH = os.environ.get('GOOGLE_DRIVE_CREDENTIALS', 'credentials.json')
SCOPES_DRIVE = ['https://www.googleapis.com/auth/drive.file']
SCOPES_SHEETS = ['https://www.googleapis.com/auth/spreadsheets']

# Configuration
SHEETS_SPREADSHEET_ID = os.environ.get('GOOGLE_SHEETS_ID', '1eSRYhP9hByoOioCs9KlUUvQUSUuI9YCKIR6CopSwEHQ')
SHEETS_RANGE = 'Sheet1!A:I'  # Columns A-I for all our fields


def get_db_connection():
    """Create database connection."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_database():
    """Initialize the SQLite database with assets table."""
    conn = get_db_connection()
    c = conn.cursor()
    c.execute('''
        CREATE TABLE IF NOT EXISTS assets (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            character_name TEXT NOT NULL,
            asset_type TEXT NOT NULL,
            asset_name TEXT NOT NULL,
            quantity INTEGER DEFAULT 1,
            location TEXT,
            isk_value REAL DEFAULT 0.0,
            notes TEXT,
            logged_datetime TEXT NOT NULL,
            status TEXT DEFAULT 'active'
        )
    ''')
    conn.commit()
    conn.close()


def get_credentials():
    """Load Google credentials."""
    if not os.path.exists(CREDENTIALS_PATH):
        return None
    
    try:
        return service_account.Credentials.from_service_account_file(
            CREDENTIALS_PATH
        )
    except Exception as e:
        print(f"Error loading credentials: {e}")
        return None


def upload_to_google_drive(asset_id, character_name, asset_type, asset_name, quantity, location, isk_value, notes, logged_datetime):
    """Upload asset details to Google Drive using Google Drive API."""
    if not GOOGLE_APIS_AVAILABLE:
        return False, 'not_configured', 'Google APIs not installed'
    
    creds = get_credentials()
    if not creds:
        return False, 'no_credentials', f'Place credentials at {CREDENTIALS_PATH}'
    
    creds = creds.with_scopes(SCOPES_DRIVE)
    
    try:
        service = build('drive', 'v3', credentials=creds)
        
        # Generate file content
        content = f"""EVE Online Asset Log
==================
Entry ID: {asset_id}
Logged: {logged_datetime}

Character: {character_name}
Asset Type: {asset_type}
Asset Name: {asset_name}
Quantity: {quantity}
Location: {location}
ISK Value: {isk_value:,.2f}

Notes: {notes}

---
Generated by EVE Online Asset Tracker v1.0
"""
        
        # Create file metadata
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"EVE_Asset_{timestamp}.txt"
        
        file_metadata = {
            'name': filename,
            'parents': ['1AOxWfQzkbXC6Uk9PVA']
        }
        
        media = MediaInMemoryUpload(content.encode(), mimetype='text/plain')
        
        file = service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id,name,webViewLink'
        ).execute()
        
        return True, file.get('id'), file.get('webViewLink')
        
    except Exception as e:
        return False, 'upload_error', str(e)


def append_to_google_sheets(asset_id, character_name, asset_type, asset_name, quantity, location, isk_value, notes, logged_datetime):
    """Append asset data to Google Sheets using Google Sheets API v4."""
    if not GOOGLE_APIS_AVAILABLE:
        return False, 'not_configured', 'Google APIs not installed'
    
    creds = get_credentials()
    if not creds:
        return False, 'no_credentials', f'Place credentials at {CREDENTIALS_PATH}'
    
    creds = creds.with_scopes(SCOPES_SHEETS)
    
    try:
        service = build('sheets', 'v4', credentials=creds)
        
        # Prepare row data
        row = [
            logged_datetime,
            character_name,
            asset_type,
            asset_name,
            quantity,
            location,
            isk_value,
            notes,
            'active'
        ]
        
        # Append row to spreadsheet
        request_body = {
            'values': [row]
        }
        
        result = service.spreadsheets().values().append(
            spreadsheetId=SHEETS_SPREADSHEET_ID,
            range=SHEETS_RANGE,
            valueInputOption='USER_ENTERED',
            insertDataOption='INSERT_ROWS',
            body=request_body
        ).execute()
        
        updates = result.get('updates', {})
        return True, str(updates.get('updatedRows', 1)), f"Appended to {SHEETS_SPREADSHEET_ID}"
        
    except Exception as e:
        return False, 'sheets_error', str(e)


def send_email_via_zapier(character_name, asset_type, asset_name, quantity, location, isk_value, logged_datetime):
    """Send email notification via Zapier MCP (Gmail only - Outlook blocked by MCP limitation)."""
    import subprocess
    import json
    
    email_results = {'outlook': 'MANUAL_ONLY', 'gmail': None}
    
    # Email content
    subject = f"EVE Asset Logged: {asset_name}"
    body = f"""EVE Online Asset Notification
=============================
Character: {character_name}
Asset Type: {asset_type}
Asset Name: {asset_name}
Quantity: {quantity}
Location: {location}
ISK Value: {isk_value:,.2f}
Logged: {logged_datetime}

This is an automated notification from EVE Asset Tracker.
"""
    
    # Gmail works programmatically with array format
    try:
        result = subprocess.run([
            'npx', 'mcporter', 'call', 'zapier.gmail_send_email',
            f'Send email from realmeltuc@gmail.com to melvinodelltucker@outlook.com',
            f'Show confirmation message with sent status',
            f'to=["melvinodelltucker@outlook.com"]',
            f'subject={subject}',
            f'body={body}'
        ], capture_output=True, text=True, timeout=30)
        
        if result.returncode == 0:
            if '"status":"SUCCESS"' in result.stdout or '"id":"' in result.stdout:
                email_results['gmail'] = 'SUCCESS'
            elif 'SUCCESS' in result.stdout:
                email_results['gmail'] = 'SUCCESS'
            else:
                email_results['gmail'] = 'UNKNOWN'
        else:
            email_results['gmail'] = f'ERROR'
    except Exception as e:
        email_results['gmail'] = f'EXCEPTION'
    
    return email_results


def send_telegram_notification(asset_name, character_name, location, phase_count=6):
    """Send Telegram notification via OpenClaw message tool."""
    import subprocess
    import json
    
    message = f"""✅ EVE Asset Tracker Update
━━━━━━━━━━━━━━━━━━
Asset: {asset_name}
Character: {character_name}
Location: {location}
Phases Complete: {phase_count}/8

🔄 In Progress: Phase 7 (Telegram)
📋 Pending: Phase 8 (Validation)
"""
    
    try:
        result = subprocess.run([
            'node', '/Users/meltuc/.npm-global/lib/node_modules/openclaw/openclaw.mjs', 'message', 'send',
            '--channel', 'telegram',
            '--target', '7742254346',
            '--message', message,
            '--json'
        ], capture_output=True, text=True, timeout=15)
        
        if result.returncode == 0:
            return True, 'SUCCESS'
        else:
            return False, f'ERROR: {result.stderr}'
    except Exception as e:
        return False, f'EXCEPTION: {str(e)}'


@app.route('/')
def index():
    """Render the asset tracking form."""
    return render_template('index.html')


@app.route('/submit', methods=['POST'])
def submit_asset():
    """Handle form submission and save to database."""
    conn = get_db_connection()
    c = conn.cursor()
    
    # Extract form data
    character_name = request.form.get('character_name', '')
    asset_type = request.form.get('asset_type', '')
    asset_name = request.form.get('asset_name', '')
    quantity = int(request.form.get('quantity', 1))
    location = request.form.get('location', '')
    isk_value = float(request.form.get('isk_value', 0.0))
    notes = request.form.get('notes', '')
    logged_datetime = request.form.get('logged_datetime', datetime.now().isoformat())
    
    # Insert into database
    c.execute('''
        INSERT INTO assets (character_name, asset_type, asset_name, quantity, location, isk_value, notes, logged_datetime)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (character_name, asset_type, asset_name, quantity, location, isk_value, notes, logged_datetime))
    
    asset_id = c.lastrowid
    conn.commit()
    conn.close()
    
    # Upload to Google Drive (if configured)
    drive_success, drive_id, drive_link = upload_to_google_drive(
        asset_id, character_name, asset_type, asset_name,
        quantity, location, isk_value, notes, logged_datetime
    )
    
    # Append to Google Sheets (if configured)
    sheets_success, sheets_id, sheets_status = append_to_google_sheets(
        asset_id, character_name, asset_type, asset_name,
        quantity, location, isk_value, notes, logged_datetime
    )
    
    # Build status message
    status_parts = [f'Asset logged! Entry ID: {asset_id}']
    
    if drive_success:
        status_parts.append(f'Drive: ✓')
    elif drive_id == 'no_credentials':
        status_parts.append('Drive: Setup required')
    
    if sheets_success:
        status_parts.append(f'Sheets: ✓ Row {sheets_id}')
    elif sheets_id == 'no_credentials':
        status_parts.append('Sheets: Setup required')
    else:
        status_parts.append(f'Sheets: {sheets_status}')
    
    # Send email notifications
    email_results = send_email_via_zapier(
        character_name, asset_type, asset_name,
        quantity, location, isk_value, logged_datetime
    )
    
    outlook_status = email_results.get('outlook', 'NOT_SENT')
    gmail_status = email_results.get('gmail', 'NOT_SENT')
    
    status_parts.append(f'Email: Outlook={outlook_status}, Gmail={gmail_status}')
    
    # Send Telegram notification
    telegram_success, telegram_status = send_telegram_notification(
        asset_name, character_name, location, phase_count=6
    )
    
    if telegram_success:
        status_parts.append('Telegram: ✓')
    else:
        status_parts.append(f'Telegram: {telegram_status}')
    
    flash(' | '.join(status_parts), 'success')
    
    return redirect(url_for('index'))


@app.route('/assets')
def list_assets():
    """Display recent asset entries."""
    conn = get_db_connection()
    assets = conn.execute('SELECT * FROM assets ORDER BY id DESC LIMIT 10').fetchall()
    conn.close()
    return jsonify([dict(row) for row in assets])


@app.route('/health')
def health():
    """Health check endpoint."""
    return jsonify({
        'status': 'healthy',
        'timestamp': datetime.now().isoformat(),
        'google_apis_configured': GOOGLE_APIS_AVAILABLE,
        'sheets_id': SHEETS_SPREADSHEET_ID
    })


if __name__ == '__main__':
    # Initialize database
    init_database()
    
    # Run Flask application on port 5001
    app.run(host='0.0.0.0', port=5001, debug=True)
